
#include "pitches.h"

#define BUZZER_PIN 14



void setup() {
  pinMode(BUZZER_PIN, OUTPUT);

}

void loop() {
  tone(BUZZER_PIN, NOTE_G3); // Send 1KHz sound signal...
  delay(1000);
  tone(BUZZER_PIN, 0); // Send 1KHz sound signal...
  delay(100);
  tone(BUZZER_PIN, NOTE_D4); // Send 1KHz sound signal...
  delay(1000);
  tone(BUZZER_PIN, 0); // Send 1KHz sound signal...
  delay(100);
  tone(BUZZER_PIN, NOTE_G3); // Send 1KHz sound signal...
  delay(1000);
  tone(BUZZER_PIN, 0); // Send 1KHz sound signal...
  delay(100);
  tone(BUZZER_PIN, NOTE_F4); // Send 1KHz sound signal...
  delay(1000);
  tone(BUZZER_PIN, NOTE_G3); // Send 1KHz sound signal...
  delay(2000);
  tone(BUZZER_PIN, 0); // Send 1KHz sound signal...
  delay(100); 
  tone(BUZZER_PIN, NOTE_G4); // Send 1KHz sound signal...
  delay(2000);
  tone(BUZZER_PIN, NOTE_A4); // Send 1KHz sound signal...
  delay(1000);
  tone(BUZZER_PIN, 0); // Send 1KHz sound signal...
  delay(100);
  tone(BUZZER_PIN, NOTE_A4); // Send 1KHz sound signal...
  delay(1000);
  tone(BUZZER_PIN, 0); // Send 1KHz sound signal...
  delay(100);
  tone(BUZZER_PIN, NOTE_A4); // Send 1KHz sound signal...
  delay(1000);
  tone(BUZZER_PIN, 0); // Send 1KHz sound signal...
  delay(100);
  tone(BUZZER_PIN, NOTE_A4); // Send 1KHz sound signal...
  delay(1000);
  tone(BUZZER_PIN, 0); // Send 1KHz sound signal...
  delay(100); 
  tone(BUZZER_PIN, NOTE_G4); // Send 1KHz sound signal...
  delay(4000);

}
